### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by soehlert** [bechurch/DrinkBot#1]
This is what happens when I do npm start from ~/projects/DrinkBot/

```
> drink-bot@1.0.0 start /home/user/projects/DrinkBot
> node --harmony_arrow_functions app.js

Error: unrecognized flag --harmony_arrow_functions
Try --help for options

/home/user/projects/DrinkBot/lib/DrinkBot.js:17
        var tasteString = recipe.tastes.map( taste => taste.text ).join(", ");
                                                    ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/sam/projects/DrinkBot/app.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by bnchrch** [comment]
@soehlert Sorry I missed this. Drinkbot requires IO.js v3 or higher to run
